### ISSUE TITLE
YouTube Video Links do not reder like other clients

### ISSUE THREAD

**Issue by PalmTreeVI** [nostrband/nostrsite#10]
Not sure if it is theme specific or if it's problem elsewhere but YouTube links don't render just eternal spinning box

Current theme: simply v.0.4.0

![Screenshot_2024-12-12_11-20-20](https://github.com/user-attachments/assets/0012010a-129a-49e4-bb05-df677bc93bc1)

**Comment by nostrband** [comment]
Does it not resolve if you reload the page? It should spin for a while and either spinner disappears if it failed to fetch the embedded player, or it should be replaced with the video. Maybe we should add a timeout there. Any errors in console? Thanks.

**Comment by PalmTreeVI** [comment]
It never resolves even after multiple refreshes on both Chrome and Firefox. It just spins forever.  

![Screenshot_2024-12-12_15-49-57](https://github.com/user-attachments/assets/56c4b149-d164-41b4-827c-75bc54589941)

**Comment by PalmTreeVI** [comment]
OK, it has to do with the youtube url, in the post:
`https://www.youtube.com/watch?v=ezSnXNTJPbQ?autoplay=1`

it is translated into:
```https://www.youtube.com/oembed?format=json&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DezSnXNTJPbQ%3Fautoplay%3D1&maxwidth=680``` which returns "Bad Request"

if `%3Fautoplay` is changed to `&autoplay` it works correctly and resolves.

**Comment by PalmTreeVI** [comment]
After looking closely at the users text string, they typed it in wrong - user error!!!

**Comment by nostrband** [comment]
Ah yes, exactly!
