### ISSUE TITLE
Setting Long-form posts in Content Filters always reverts to displaying Notes Instead of Long Form Content

### ISSUE THREAD

**Issue by PalmTreeVI** [nostrband/nostrsite#5]
In admin, I changed the Content Filter to show only "Long-form Posts". Regardless of this setting site is populated with Notes instead of "Long-form Posts". It ocassionally works just after changing this setting but always reverts to Notes.

**Comment by nostrband** [comment]
Hi apologies about that, fixed it for your site. Latest site event wasn't published on our relay, and another issue didn't let us fetch it from your outbox relays. 

We've created another issue for this case, and your site should be fine now, is it?

**Comment by PalmTreeVI** [comment]
Yes, seems to be working correctly now.
