### ISSUE TITLE
Code injection in header saves on admin dashboard but doesn't update on the site

### ISSUE THREAD

**Issue by PalmTreeVI** [nostrband/nostrsite#6]
"Code injection in header" saves on the admin dashboard but doesn't update on the site even after clearing browser cache or using a private window. It sometimes works on the first page load after making changes but always reverts back to an older setting after a few moments.

**Comment by nostrband** [comment]
Similar to #7

**Comment by nostrband** [comment]
Should be fixed by https://github.com/nostrband/nostr-site-manager/pull/131 
@leafes please check, edit a site and check logs for "published site event ..." message, it should include "relay.npubpro.com"

**Comment by nostrband** [comment]
@PalmTreeVI please check on your end if it's working reliably now. Thanks.

**Comment by PalmTreeVI** [comment]
I was able to delete all sites and start over. Everything so far has worked as expected. I'm going to try the same on a different another which had more issues than the first.

**Comment by PalmTreeVI** [comment]
Seems to be working now!

**Comment by leafes** [comment]
rechecked, issue is fixed now
