### ISSUE TITLE
Feature Suggestion - Use Accent Color in meta Info

### ISSUE THREAD

**Issue by PalmTreeVI** [nostrband/nostrsite#9]
Would be awesome to add already established "Accent Color" to these new tags:
```html
<meta name="theme-color" content="#xxxxxx">
<meta name="msapplication-TileColor" content="#xxxxxx">
```
xxxxxx = accent color

**Comment by nostrband** [comment]
Done, published on https://palmtree.npub.pro/, will propagate to others later on. Please check, thanks!
